version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: database
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    networks:
      - braciate_staging_network
      - braciate_prod_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    restart: always

  backend-prod:
    container_name: "backend-prod"
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    networks:
      - braciate_prod_network
    env_file:
      - .prod.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    restart: always

  backend-staging:
    container_name: "backend-staging"
    build:
      context: .
      dockerfile: Dockerfile
      target: staging
    networks:
      - braciate_staging_network
    env_file:
      - .staging.env
    ports:
      - "3001:3000"
    depends_on:
      - backend-prod
    restart: always

networks:
  braciate_staging_network:
    driver: bridge
    name: braciate_staging_network
  braciate_prod_network:
    driver: bridge
    name: braciate_prod_network

volumes:
  postgres_data:
