version: "3.8"

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_SSLMODE=disable
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_TOKEN=${SUPABASE_TOKEN}
    depends_on:
      - db

  db:
    image: "postgres"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=postgres
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
